# WARNING: Change JAVA_HOME accordingly on version change
FROM debian:bullseye-slim

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANGUAGE en_US:en

# Install dependencies for the jenkins_agent.sh
RUN apt update && \
    apt install -y curl procps openjdk-11-jre-headless && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

COPY jenkins_agent.sh /srv/jenkins_agent/jenkins_agent.sh

# Jenkins agent variables
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

WORKDIR /root
STOPSIGNAL SIGINT
ENTRYPOINT ["/srv/jenkins_agent/jenkins_agent.sh"]
